#!/usr/bin/env python
# bolt-executor
import argparse
import os
import subprocess
import sys


parser = argparse.ArgumentParser(description='Run Bolt command.')
parser.add_argument('username', help='the username')
parser.add_argument('hostname', help='the hostname')
args = parser.parse_args()

exec_command = os.getenv("RD_EXEC_COMMAND") 

protocol = os.getenv("RD_CONFIG_PROTOCOL") 
host=protocol +"://"+args.hostname
use_ssl = os.getenv("RD_CONFIG_WINRM_SSL")

COMMAND = ["/usr/local/bin/bolt", "command", "run", exec_command,"-n", host,"-u",args.username]

if "RD_CONFIG_PASSWORD_STORAGE_PATH" in os.environ:
    COMMAND.append("-p")
    COMMAND.append(os.getenv("RD_CONFIG_PASSWORD_STORAGE_PATH"))

if protocol == "ssh":
    COMMAND.append("--tty")

if use_ssl != true:
	COMMAND.append("--no-ssl")

if os.getenv("RD_JOB_LOGLEVEL") == "DEBUG":
    COMMAND.append("--debug")

if os.getenv("RD_CONFIG_DRY_RUN") == "true":
    print '[%s]' % ', '.join(map(str, COMMAND))
else:

	try:

	    retcode = subprocess.call(COMMAND)
	    sys.exit(retcode)
	except OSError as e:
	    print >>sys.stderr, "Command error:", e
	    sys.exit(1)

# Done
